## Numpy Lab

In [1]:
import numpy as np

def n_size_ndarray_creation(n, dtype=np.int):
    X = np.array(range(n**2),dtype=dtype).reshape(n,n)
    return X

n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
def zero_or_one_or_empty_ndarray(shape, type, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=dtype)
    if type == 1:
        return np.ones(shape=shape, dtype = dtype)
    if type == 99:
        return np.empty(shpae=shape, dtype = dtype)
    
zero_or_one_or_empty_ndarray(shape=(3,3),type=1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row==1 else X.reshape(n_row,-1)

X = np.ones((32,32), dtype = np.int)
change_shape_of_ndarray(X, 4)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [4]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1,-1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1,-1)
        return np.concatenate((X_1,X_2),axis=axis)    
    except ValueError as e:
        return False

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

concat_ndarray(a,b,0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column = X.shape
    if axis == 99:
        x_mean = np.mean(X)
        x_std = np.std(X)
        Z = (X-x_mean)/x_std
    if axis == 0:
        x_mean = np.mean(X,0).reshape(1,-1)
        x_std = np.std(X,0).reshape(1,-1)
        Z = (X-x_mean)/x_std
    if axis == 1:
        x_mean = np.mean(X,1).reshape(n_row,-1)
        x_std = np.std(X,1).reshape(n_row,-1)
        Z = (X-x_mean)/x_std
    return Z

X = np.arange(12, dtype=np.float32).reshape(6,2)
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [6]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename,'wb')
    np.save(X, file_test)

In [7]:
def boolean_index(X, condition):
    condition = eval(str("X")+condition)
    return np.where(condition)

X = np.arange(32, dtype=np.float32)
boolean_index(X, ">10")

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31], dtype=int64),)

In [8]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

X = np.random.uniform(0,1,5)
find_nearest_value(X, 3)

0.9734580726796742

In [9]:
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

X = np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)

array([0.38460611, 0.78804628, 0.93970109])

## Lab Build Matrix