In [1]:
import numpy as np

## Array creation

In [5]:
test_array = np.array([1,4,5,8],int)
print(test_array)
test_array = np.array([1,4,5,8],float)
print(test_array)

[1 4 5 8]
[1. 4. 5. 8.]


In [7]:
type(test_array[3])

numpy.float64

In [8]:
test_array.dtype

dtype('float64')

## Array Shape

In [9]:
test_array.shape #배열의 shape을 반환

(4,)

In [11]:
np.array([[1,4,5,8]],int).shape

(1, 4)

### ndim & size

In [16]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

In [17]:
np.array(tensor,int).ndim #number of dimension

3

In [19]:
np.array(tensor,int).size #data의 개수

48

## Handling shape

### reshape

In [20]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [21]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [24]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [25]:
test = np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [26]:
np.array(test_matrix).reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

### flatten

In [27]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

## Indexing & Slicing

### indexing

In [28]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)
print(a[0,0])
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [30]:
a[0,0] = 12
print(a)
a[0][0] = 5
print(a)

[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


### slicing

In [31]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [32]:
a[1,1:3]

array([7, 8])

In [35]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

## creation function

### arange

In [36]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [39]:
np.arange(0,5,0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [38]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros and  empty

In [43]:
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [44]:
np.ones(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [50]:
np.empty(shape=(10,),dtype=np.int8) #shpae만 주어지고 비어있는 ndarray생성

array([-48,  93,   9,  84, 109,   2,   0,   0,   0,   0], dtype=int8)

### something_like

In [51]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### identity

In [54]:
np.identity(n=3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### eye

In [59]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [60]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diag

In [63]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

### random sampling

In [64]:
np.random.uniform(0,1,10).reshape(2,5) #균등분포

array([[0.57208283, 0.7378286 , 0.40544595, 0.79418936, 0.19007389],
       [0.68087269, 0.14522558, 0.04319176, 0.06570817, 0.33393041]])

In [65]:
np.random.normal(0,1,10).reshape(2,5) #정규분포

array([[-0.49198176,  0.32381073,  0.58126122, -0.87113671, -0.44911302],
       [ 0.99008396, -0.60735334, -0.44147394,  0.95099945,  0.47445945]])

## operation function

### sum

In [66]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
test_array.sum()

55

### axis

In [70]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

### concatenate

In [72]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [73]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [81]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [84]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## array operations

### Operations b/t arrays

In [89]:
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [90]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [91]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### Element-wise operations

In [95]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### Dot Product

In [99]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
print(test_a)
print(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [100]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### transpose

In [101]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [103]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### broadcasting

In [104]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [105]:
test_matrix * 3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

### numpy performance

In [107]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*value)
    return result

iternation_max = 10000000

vector = list(range(iternation_max))
scalar = 2

%timeit scalar_vector_product(scalar, vector)

2.35 s ± 216 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [108]:
%timeit [scalar * value for value in range(iternation_max)]
%timeit np.arange(iternation_max) * scalar

3.29 s ± 928 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
97.5 ms ± 16.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## comparisons

### all & any

In [109]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [111]:
np.any(a>5), np.any(a<0)

(True, False)

In [112]:
np.all(a>5), np.all(a<10)

(False, True)

### comparision operation

In [114]:
a = np.array([1,3,0],float)
np.logical_and(a>0,a<3)

array([ True, False, False])

In [115]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [116]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True,  True])

### np.where

In [119]:
np.where(a>0,3,2)
a, np.where(a>0,3,2)

(array([1., 3., 0.]), array([3, 3, 2]))

In [120]:
np.where(a>0)

(array([0, 1], dtype=int64),)

In [123]:
a = np.array([1,np.NaN,np.Inf],float)
np.isnan(a)

array([False,  True, False])

In [125]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin

In [127]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [129]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a,axis=1), np.argmin(a,axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

### boolean index

In [130]:
a = np.array([1,2,4,5,8,78,23,3])
a > 3

array([False, False,  True,  True,  True,  True,  True, False])

In [131]:
a[a>3]

array([ 4,  5,  8, 78, 23])

In [133]:
condition = a < 3
a[condition]

array([1, 2])

In [135]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B

array([[ True,  True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True],
       [ True,  True, False, False,  True, False, False,  True,  True],
       [ True,  True, False,  True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False, 

In [136]:
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

### fancy index

In [142]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 2, 3, 0], int)
a[b]

array([2., 2., 4., 6., 8., 2.])

In [143]:
a.take(b)

array([2., 2., 4., 6., 8., 2.])