## Numpy Lab

In [6]:
import numpy as np

def n_size_ndarray_creation(n, dtype=np.int):
    X = np.array(range(n**2),dtype=dtype).reshape(n,n)
    return X

n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
def zero_or_one_or_empty_ndarray(shape, type, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=dtype)
    if type == 1:
        return np.ones(shape=shape, dtype = dtype)
    if type == 99:
        return np.empty(shpae=shape, dtype = dtype)
    
zero_or_one_or_empty_ndarray(shape=(3,3),type=1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row==1 else X.reshape(n_row,-1)

X = np.ones((32,32), dtype = np.int)
change_shape_of_ndarray(X, 4)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [44]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1,-1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1,-1)
        return np.concatenate((X_1,X_2),axis=axis)    
    except ValueError as e:
        return False

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

concat_ndarray(a,b,0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column = X.shape
    if axis == 99:
        x_mean = np.mean(X)
        x_std = np.std(X)
        Z = (X-x_mean)/x_std
    if axis == 0:
        x_mean = np.mean(X,0).reshape(1,-1)
        x_std = np.std(X,0).reshape(1,-1)
        Z = (X-x_mean)/x_std
    if axis == 1:
        x_mean = np.mean(X,1).reshape(n_row,-1)
        x_std = np.std(X,1).reshape(n_row,-1)
        Z = (X-x_mean)/x_std
    return Z

X = np.arange(12, dtype=np.float32).reshape(6,2)
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [50]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename,'wb')
    np.save(X, file_test)

In [54]:
def boolean_index(X, condition):
    condition = eval(str("X")+condition)
    return np.where(condition)

X = np.arange(32, dtype=np.float32)
boolean_index(X, ">10")

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31], dtype=int64),)

In [58]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

X = np.random.uniform(0,1,5)
find_nearest_value(X, 3)

0.9041691015544712

In [61]:
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

X = np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)

array([0.40820804, 0.68041541, 0.92518004])

## Lab Build Matrix

In [66]:
import pandas as pd
def get_rating_matrix(filename, dtype=np.float32):
    df = pd.read_csv(filename)
    return df.groupby(["source","target"])["rating"].sum().unstack().fillna(0)

get_rating_matrix("C:/Users/qual9/movie_rating.csv")

target         Just My Luck  Lady in the Water  Snakes on a Plane  \
source                                                              
Claudia Puig            3.0                0.0                3.5   
Gene Seymour            0.0                3.0                3.5   
Jack Matthews           0.0                3.0                4.0   
Lisa Rose               3.0                2.5                3.5   
Mick LaSalle            2.0                3.0                4.0   
Toby                    0.0                0.0                4.5   

target         Superman Returns  The Night Listener  You Me and Dupree  
source                                                                  
Claudia Puig                0.0                 4.5                0.0  
Gene Seymour                0.0                 3.0                3.5  
Jack Matthews               5.0                 3.0                3.5  
Lisa Rose                   3.5                 3.0                2.5  
Mick LaSalle                3.0                 3.0                0.0  
Toby                        4.0                 0.0                0.0

In [68]:
def get_frequent_matrix(filename, dtype=np.float32):
    df = pd.read_csv(filename)
    df["rating"] = 1
    return df.groupby(["source","target"])["rating"].sum().unstack().fillna(0)

get_frequent_matrix("C:/Users/qual9/1000i.csv")

target  0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
source                                          ...                           
1       19  17  14  11  17  25   7  22   5  18  ...  15  14  20   9  12  16   
2       20  16  10  15  17  18  10  13   5  19  ...  13  12  15   9  13  16   
3       12  16  13  19  23  19   5  14   5  18  ...  10  14  10  17  15  16   
4       14  14  19  11  11  18   7  16   7  17  ...   9  16  18  12  16  16   
5       13   7   8  15  13  16   3  19  11  12  ...  11  10  16   8  13  20   

target  46  47  48  49  
source                  
1       11   9  11  12  
2       16  10  16   9  
3       11  17   9  11  
4       26  16  12  20  
5       14  18  21   3  

[5 rows x 50 columns]